myWebsite/myWebsite/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from my_website_app import views

urlpatterns = [
    path('', views.landing, name='index'),
    path('home/', views.index, name='home'),
    path('contact/', views.contact, name='contact'),
    path('project/', include('project_app.urls')),
    path('user/', include('user_app.urls')),
    path('topic/', include('topic_app.urls')),
    path('admin/', admin.site.urls),
]

myWebsite/project_app/urls.py
from django.urls import path
from project_app import views

app_name = 'project_app'

urlpatterns = [

    path('topic_form/', views.topicForm, name='topic_form'),
    path('topics/', views.researchTopics, name='topics'),
]

myWebsite/topic_app/urls.py
from django.urls import path, include
from topic_app import views

app_name = 'topic_app'

urlpatterns = [
    path('discussion/', views.discussion, name='discussion'),

]

myWebsite/user_app/urls.py
from django.urls import path
from user_app import views

app_name = 'user_app'


urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
]

myWebsite/my_website_app/models.py
from django.db import models


# Create your models here.
class UserEnquiries(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    enquiry_title = models.CharField(max_length=150)
    message = models.CharField(max_length=4000)

    def __str__(self):
        return self.enquiry_title

myWebsite/project_app/models.py
from django.db import models

# Create your models here.

myWebsite/topic_app/models.py
from django.db import models

# Create your models here.

myWebsite/user_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):

    # this create a 1 to 2 relationship with the Users class
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

myWebsite/my_website_app/forms.py
from django import forms
from django.core import validators
from my_website_app.models import UserEnquiries


class UserEnquiriesForm(forms.ModelForm):
    message = forms.CharField(max_length=3000, widget=forms.Textarea(attrs={'cols': 100, 'rows': 5}))
    class Meta:
        model = UserEnquiries
        fields = '__all__'

myWebsite/user_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from user_app.models import UserProfile


class UserForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter first name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter last name'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter username'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter password'}))
    v_pw = forms.CharField(label='Verify Password', widget=forms.PasswordInput(attrs={'placeholder': 'Verify password'}))

    def clean(self):
        cleaned_data = super().clean()

        clean_pw = cleaned_data['password']
        clean_vpw = cleaned_data['v_pw']

        if clean_pw != clean_vpw:
            raise forms.ValidationError('Both passwords must match')

    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password', 'v_pw')


# class UserProfileForm(forms.ModelForm):
#
#     first_name = forms.CharField(label='First Name')
#     last_name = forms.CharField(label='Last Name')
#
#     class Meta():
#         model = UserProfile
#         fields = ('first_name', 'last_name')

myWebsite/my_website_app/views.py
from django.shortcuts import render
from my_website_app.forms import UserEnquiriesForm

# Create your views here.


def landing(request):
    return render(request, 'my_website_app/landing.html')


def index(request):
    return render(request, 'my_website_app/index.html')


def contact(request):

    submitted = False

    if request.method == 'POST':

        form = UserEnquiriesForm(request.POST)

        if form.is_valid:
            form.save(commit=True)

            submitted = True
    else:
        form = UserEnquiriesForm()

    return render(request, 'my_website_app/contact.html', {'form': form,
                                                           'submitted': submitted})

myWebsite/project_app/views.py
from django.shortcuts import render

# Create your views here.

def topicForm(request):
    return render(request, 'project_app/submit_topic.html')


def researchTopics(request):
    return render(request, 'project_app/research_topics.html')

myWebsite/topic_app/views.py
from django.shortcuts import render

# Create your views here.


def discussion(request):
    return render(request, 'topic_app/discussions.html')

myWebsite/user_app/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from user_app.forms import UserForm


# Create your views here.
def user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))

            else:
                return HttpResponse('User Account not Active')
        else:
            print(f'Login failed - username: {username}, password: {password}')
            return HttpResponse('Login Failed - Please try again or register if you do not have an account.')
    else:
        return render(request, 'user_app/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))


def register(request):

    registered = False

    if request.method == 'POST':

        user_form = UserForm(data=request.POST)

        if user_form.is_valid():

            user = user_form.save()
            # set the password as an actual password - django hashes this pw
            user.set_password(user.password)
            user.save()

            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm

    return render(request, 'user_app/register.html', {'user_form': user_form,
                                                      'registered': registered})

myWebsite/templates/my_website_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>
        {% block title_block %}

        {% endblock %}
    </title>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/brand.png' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    {% block css_block %}

    {% endblock %}

</head>
<body>
    <nav class="navbar navbar-inverse navbar-static-top">

            <div class="container-fluid">

                <!-- The data-target grabs ids to put into the icon -->
                <!-- Brand and toggle get grouped for better mobile display -->

                <div class="navbar-header">

                    <!--       This is the button which appear when the window is shrinked - setting the burger icon            -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <!--           This create the burger icon             -->
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                     <!-- This contains the company branding within the navbar -  notice the classes used-->
                    <a href="{% url 'index' %}" class="navbar-brand">
                        <img src="{% static "images/brand.png" %}" width="25" height="25" class="d-inline-block align-top" alt="image not found">
                    </a>
                    <a href="{% url 'index' %}" class="navbar-brand">OO</a>
                </div>

                <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
                <div class="collapse navbar-right navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="navbar-link"><a href="{% url 'home' %}">Our Mission</a></li>
                        <li class="navbar-link"><a href="{% url 'topic_app:discussion' %}">Discussion Board</a> </li>
                        <!--       Dropdown menu                 -->
                        <li>
                            {% if user.is_authenticated %}
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Research Projects/Topics<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li class="navbar-link"><a href="{% url 'project_app:topic_form' %}">Submit a Research Projects/Topic</a></li>
                                <li role="separator" class="divider"></li>
                                <li class="navbar-link"><a href="{% url 'project_app:topics' %}">Submitted Research Projects/Topics</a></li>
                            </ul>
                            {% endif %}
                        </li>
                        <li class="navbar-link "><a href="{% url 'contact' %}">Get in touch<span class="sr-only"(current)></span></a> </li>
                    </ul>

                    <!--search bar-->
                    <form class="navbar-form navbar-right" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">Search</button>
                    </form>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Join the community<span class="caret"></span></a>
                            <ul class="dropdown-menu">
<!--                                if user_app.is_authenticated - this refers to the user_app variable in the user_login view-->
                                {% if user.is_authenticated %}
                                    <li><a href="{% url 'user_app:logout' %}">Logout</a></li>
                                {% else %}
                                    <li><a href="{% url 'user_app:login' %}">Login</a></li>
                                {% endif %}
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'user_app:register' %}">Register</a></li>
                            </ul>
                        </li>
                    </ul>
                </div> <!-- end of collapse toggle-->
            </div> <!-- end of container-fluid-->
    </nav>


        {% block body_block %}

        {% endblock %}



    <footer class="page-footer footer-fixed-bottom">
<!--        <p class="copyright" align="center" style="color: white"> Copyright 2020, Alex Erentz</p>-->
<!--        <br>-->
        <ul style="list-style-type: none">
            <li class="fInfo">Contact Email </li>
            <li class="fInfo">Contact Number </li>
            <li class="fInfo">Copyright 2020, Alex Erentz</li>
            <li class="fInfo">Facebook</li>
            <li class="fInfo">LinkedIn</li>
            <li class="fInfo">Github</li>
        </ul>
    </footer>

    <style>
            footer{
                {% block footer_position_block %}
                position: relative;
                {% endblock %}

                bottom: 0px;
                left: 0px;
                right: 0;
                background-color: black;
                color: white;
                height: 80px;
                width: 100%;
                margin-bottom: -50px;

            }
         </style>

         <style>
               .fInfo{
                display: inline-block;
                margin-left: 65px;
                margin-right: 65px;
                align: center;
               }
         </style>


     <!--  jQuery script for the dropdown menus  -->
      <script
          src="http://code.jquery.com/jquery-3.1.1.js"
          integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
          crossorigin="anonymous">
      </script>  <!-- Latest compiled and minified JavaScript -->

        <!--    Javascript import from bootstrap     -->
      <script
              src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
              integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
              crossorigin="anonymous">
      </script>

        {% block style_scripts_block %}

        {% endblock %}
</body>
</html>

myWebsite/templates/my_website_app/contact.html
<!DOCTYPE html>
{% extends 'my_website_app/base.html' %}

    {% block title_block %}
        Contact
    {% endblock %}

    {% block body_block %}
        <div class="container">
            <div class="jumbotron">

                {% if submitted %}

                    <h1>Thank you for your enquiry, we have received it.
                        <br>
                        <br>
                        An admin will be in touch sharply!</h1>

                {% else %}

                    <h1 align="center">Need to get in touch?</h1>
                    <h3 align="center">Please use out form below to submit any inquiries you may have. We aim to respond to all enquiries as soon as possible.</h3>
                    <br>
                    <form enctype="multipart/form-data" method="POST" >
                        {% csrf_token %}
                        {{form.as_p}}
                    <input type="submit" class="btn btn-primary" value="Submit">
                    </form>

                {% endif %}
            </div>
        </div>

    {% endblock %}

myWebsite/templates/my_website_app/index.html
<!DOCTYPE html>
{% extends 'my_website_app/base.html' %}

    {% block title_block %}
        Home
    {% endblock %}

    {% block css_block %}
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/home_style.css' %}">
    {% endblock %}

    {% block body_block %}
        <div class="wrapper">
             <div class="container-fluid" align="center">
                <div class="jumbotron">
                    <header>
                        <h1><img src="{% static "images/brand.png" %}" width='90px', height='90px'> OOur Mission Statement </h1>

                    </header>
                </div>
            </div>

            <br>
    <!-- Grids -->
             <div id="Grid" class="container-fluid">
                 <div class="row">
                     <div class="col-lg-6 boxy" style="background-image: url({% static 'images/misInfo.jpg' %})"></div>
                     <div class="col-lg-6 boxy" style="background-image: url({% static 'images/fakeNews.jpg' %})"></div>
                 </div>
             </div>

             <div id="Grid" class="container-fluid">
                 <div class="row">
                     <div class="col-lg-3 boxy" style="background-color: white"></div>
                     <div class="col-lg-3 boxy"></div>
                     <div class="col-lg-3 boxy"></div>
                     <div class="col-lg-3 boxy" style="background-color: white"></div>
                 </div>
             </div>

             <div id="Grid" class="container-fluid">
                 <div class="row">
                     <div class="col-lg-12 boxy" style="background-image: url({% static 'images/planet2.jpg' %})"></div>
                 </div>
             </div>
        </div>




    {% endblock %}

    {% block footer_position_block %}
        position: fixed;
    {% endblock %}

myWebsite/templates/my_website_app/landing.html
<!DOCTYPE html>
{% extends 'my_website_app/base.html' %}
{% load static %}

    {% block title_block %}
        Landing
    {% endblock %}

    {% block body_block %}
        <div class="jumbotron" align="center">
            <h1><b>We hope your enjoy our space</b></h1>

           
            <form action="{% url 'home' %}">
                <button class="btn btn-primary btn-lg" id="enter_page" type="submit">Click to enter</button>
            </form>
        </div>
    {% endblock %}

    {% block footer_position_block %}
        position: fixed;
    {% endblock %}

    {% block style_scripts_block %}
        <style>
          body{
            background-image: URL("{% static 'images/space.jpg' %}");
            background-repeat: repeat;
            opacity: 0.8;
           }

            #navbar{
              opacity: 1;
            }
        </style>

        <script src="{% static 'javascript/colourChange.js' %}"></script>
    {% endblock %}

myWebsite/templates/project_app/research_topics.html
<!DOCTYPE html>
{% extends 'my_website_app/base.html'%}

    {% block title_block %}
        submitted_topics
    {% endblock %}

    {% block body_block %}

    {% endblock %}

myWebsite/templates/project_app/submit_topic.html
<!DOCTYPE html>
{% extends 'my_website_app/base.html'%}

    {% block title_block %}
        Submit topic
    {% endblock %}

    {% block body_block %}

    {% endblock %}

myWebsite/templates/topic_app/Discussions.html
<!DOCTYPE html>
{% extends 'my_website_app/base.html'%}

    {% block title_block %}
    Discussions
    {% endblock %}

    {% block body_block %}
        <div class="container-fluid" align="center">
            <div class="jumbotron">
                <header>
                    <h1>Open Discussion Board</h1>
                    <br>
                    <h2><strong>Think. Discuss. Explore.</strong></h2>
                    <br>
                    <p>Welcome to the discussion board</p>
                    <p><em>Our aim is to bring all consciousness together to identify how we can all best move forward as a race</em></p>
                    <p align="left">Here is the place where you can have your say. Please choose a relative category for your topic
                        of discussion or add a new one if it doesnt already exist. Leave your thoughts and ideas for the
                        rest of the world to see and extend on.</p>
                    <p align="left">You will find a list of topics which we feel cover the majority of the most important topics
                    surrounding us during this current point in time. Please feel free to add your own topics or even
                    sub-genre topics.</p>
                </header>
            </div>
        </div>


        <h2 style="text-decoration: underline; font-size: 50px; padding-bottom: 20px" align="center">Choose a Topic</h2>


        <div id="dTopic" class="container-fluid">
            <div class="row">
                <div class="col-lg-3 col-xs-3 boxy2" style="background-image: URL('images/tech.jpg')"></div>
                <div class="col-lg-3 col-xs-3 boxy1" style="background-image: URL('images/tech2.jpg')"></div>
                <div class="col-lg-3 col-xs-3 boxy1" style="background-image: URL('images/tech3.jpg')"></div>
                <div class="col-lg-3 col-xs-3 boxy1" align="center" style="font-size: 30px; text-decoration: underline"><br><br><a href="#"><strong>Technology</strong></a> <br><br> Click here for sub-categories</div>
            </div>
        </div>

        <div role="separator" class="divider"></div>

        <div id="dTopic" class="container-fluid">
            <div class="row">
                <div class="col-lg-3 col-xs-3 boxy2" align="center" style="font-size: 30px; text-decoration: underline"><br><br><a href="#"><strong>Science</strong></a> <br><br> Click here for sub-categories</div>
                <div class="col-lg-3 col-xs-3 boxy1" style="background-image: URL('images/science.jpg')"></div>
                <div class="col-lg-3 col-xs-3 boxy1" style="background-image: URL('images/science2.jpg')"></div>
                <div class="col-lg-3 col-xs-3 boxy1" style="background-image: URL('images/science3.jpg')"></div>
            </div>
        </div>

        <div id="dTopic" class="container-fluid">
            <div class="row">
                <div class="col-lg-3 col-xs-3 boxy2" style="background-image: URL('images/health.jpg')"></div>
                <div class="col-lg-3 col-xs-3 boxy1" style="background-image: URL('images/health2.jpg')"></div>
                <div class="col-lg-3 col-xs-3 boxy1" style="background-image: URL('images/health3.jpg')"></div>
                <div class="col-lg-3 col-xs-3 boxy1" align="center" style="font-size: 30px; text-decoration: underline"><br><br><a href="#"><strong>Health</strong></a> <br><br> Click here for sub-categories</div>
            </div>
        </div>

        <div id="dTopic" class="container-fluid">
            <div class="row">
                <div class="col-lg-3 col-xs-3 boxy2" align="center" style="font-size: 30px; text-decoration: underline"><br><br><a href="#"><strong>Social Constructs</strong></a> <br><br> Click here for sub-categories</div>
                <div class="col-lg-3 col-xs-3 boxy1" style="background-image: URL('images/social1.jpg')"></div>
                <div class="col-lg-3 col-xs-3 boxy1" style="background-image: URL('images/social2.jpg')"></div>
                <div class="col-lg-3 col-xs-3 boxy1" style="background-image: URL('images/social3.jpg')"></div>
            </div>
        </div>

        <div id="dTopic" class="container-fluid">
            <div class="row">
                <div class="col-lg-3 col-xs-3 boxy1" style="background-image: URL('images/enviro3.jpg')"></div>
                <div class="col-lg-3 col-xs-3 boxy1" style="background-image: URL('images/enviro2.jpg')"></div>
                <div class="col-lg-3 col-xs-3 boxy1" style="background-image: URL('images/enviro.jpg')"></div>
                <div class="col-lg-3 col-xs-3 boxy2" align="center" style="font-size: 30px; text-decoration: underline"><br><br><a href="#"><strong>Environment</strong></a> <br><br> Click here for sub-categories</div>
            </div>
        </div>

        <div id="dTopic" class="container-fluid">
            <div class="row">
                <div class="col-lg-3 col-xs-3 boxy1" align="center" style="font-size: 30px; text-decoration: underline"><br><br><a href="#"><strong>Add New Topic Category</strong></a> <br><br> Click here for sub-categories</div>
                <div class="col-lg-3 col-xs-3 boxy1" align="center" style="font-size: 30px; text-decoration: underline; background-color: green"></div>
                <div class="col-lg-3 col-xs-3 boxy1" align="center" style="font-size: 30px; text-decoration: underline; background-color: yellow"></div>
                <div class="col-lg-3 col-xs-3 boxy2" align="center" style="font-size: 30px; text-decoration: underline; background-color: blue"><strong></strong></div>
            </div>
        </div>

    {% endblock %}

    {% block footer_position_block %}
        position: fixed;
    {% endblock %}

myWebsite/templates/user_app/login.html
<!DOCTYPE html>
{% extends 'my_website_app/base.html' %}

    {% block title_block %}
        Login
    {% endblock %}

    {% block body_block %}
        <div class="container">
            <div class="jumbotron" align="center">
                <h1>Welcome to the login page</h1>
                <form action="{% url 'user_app:login' %}" method="post">

                     {% csrf_token %}

                    <label for="username">Username: </label>
                    <input type="text" name="username" placeholder="Enter Username">
                    <br>
                    <br>
                    <label for="password">Password: </label>
                    <input type="password" name="password" placeholder="Enter Password">
                    <br>
                    <br>
                    <input type="submit" class="btn btn-primary" value="login">
                </form>
            </div>

            <div class="container" >
                <p>If you dont have an account please <a href="{% url 'user_app:register' %}">register</a> here.</p>
            </div>
        </div>

    {% endblock %}

    {% block footer_position_block %}
        position: fixed;
    {% endblock %}

myWebsite/templates/user_app/register.html
<!DOCTYPE html>
{% extends 'my_website_app/base.html'%}

    {% block title_block %}
        Register
    {% endblock %}

    {% block body_block %}
        <div class="container">
            <div class="jumbotron" align="center">
                {% if registered %}
                    <h1>Thank you for registering, we hope your enjoy our community!</h1>
                {% else %}
                    <h1>Register an Account!</h1>
                    <h3>Please fill out the form below to register.</h3>
                    <br>
                    <form enctype="multipart/form-data" align='left' method="post">
                        {% csrf_token %}
                        {{ user_profile_form.as_p }}
                        {{ user_form.as_p }}

                        <input type="submit" class="btn btn-primary" value="Register">
                    </form>
                {% endif %}
            </div>

             <div class="container" >
                <p>If you have an account please <a href="{% url 'user_app:login' %}">login</a> here.</p>
            </div>


        </div>

    {% endblock %}

    {% block footer_position_block %}
        position: relative;
    {% endblock %}